spring:
  profiles:
    active: dev

server:
  port: 8089
  servlet:
    context-path: /

management:
  port: 8088
  contextPath: /manage
  security:
    enabled: false

mybatis:
  mapperLocations: classpath*:/**/mybatis/**/*Repository.xml
  typeAliasesPackage: com.tasly.yzpt.repository.**.entity
  configLocation: classpath:mybatis-config.xml